version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_recruiting
    environment:
      MONGO_INITDB_DATABASE: recruiting
    ports:
      - 27017:27017
    volumes:
      - .mongodata:/data/db
volumes:
  mongodata: